version: '3.10'

services:
  streamlit:
    container_name: streamlit
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    expose:
      - "8501"
    ports:
      - "8501:8501"
    networks:
      - appnet

  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - appnet

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8010:8010"
    depends_on:
      - streamlit
      - fastapi
    networks:
      - appnet

networks:
  appnet:
