version: '3.10'
services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501"
    networks:
      - appnet

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000"
    networks:
      - appnet

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8010:8010"
    depends_on:
      - streamlit
      - fastapi
    networks:
      - appnet

networks:
  appnet:
