FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    UV_SYSTEM_PYTHON=1

RUN pip install uv

WORKDIR /app

COPY pyproject.toml uv.lock* ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen

COPY . .

ENV PATH="/app/.venv/bin:${PATH}"
EXPOSE 8010

CMD ["uvicorn", "api:app","--host","0.0.0.0", "--port", "8010"]